"""
ambiguity.py — Differentiable ambiguity function loss
Generated by 03_ambiguity_function.ipynb

Reference: Ziemann & Metzler (2024), equations (12)–(16)
"""

import torch
import torch.nn as nn


def compute_ambiguity(s: torch.Tensor,
                      n_doppler: int = 64) -> torch.Tensor:
    """
    Compute the full ambiguity surface for visualisation.

    Parameters
    ----------
    s         : (B, 2, N)  IQ signals, channels-first
    n_doppler : int        Number of Doppler bins to return

    Returns
    -------
    (B, N, n_doppler)  Real-valued ambiguity surface
    """
    B, _, N = s.shape
    s_c = torch.complex(s[:, 0, :], s[:, 1, :])
    lag_products = torch.stack(
        [s_c * torch.roll(s_c.conj(), shifts=k, dims=1)
         for k in range(N)],
        dim=1,
    )
    doppler = torch.fft.fft(lag_products, dim=2)[:, :, :n_doppler]
    return torch.abs(doppler)


class AmbiguityLoss(nn.Module):
    """
    Ambiguity function loss from Ziemann & Metzler (2024).

    Penalises generated waveforms for:
    1. Mainlobe (τ=0, f_D=0) smaller than target_peak
    2. Non-zero sidelobes (all other (τ, f_D))

    Parameters
    ----------
    n_doppler           : int    Doppler bins (paper: 256)
    target_peak         : float  Target mainlobe amplitude χ (paper: 1000)
    zero_doppler_weight : float  Sidelobe weight γ (paper: 1000)
    n_delays            : int    Delay bins for sidelobe loss (paper: full N)
    """

    def __init__(self,
                 n_doppler: int = 256,
                 target_peak: float = 1000.0,
                 zero_doppler_weight: float = 1000.0,
                 n_delays: int = 128):
        super().__init__()
        self.n_doppler = n_doppler
        self.chi       = target_peak
        self.gamma     = zero_doppler_weight
        self.n_delays  = n_delays

    def forward(self, s: torch.Tensor) -> torch.Tensor:
        B, _, N = s.shape
        s_c = torch.complex(s[:, 0, :], s[:, 1, :])

        # mainlobe loss
        lag_zero  = s_c * s_c.conj()
        dft_zero  = torch.fft.fft(lag_zero, dim=1)
        mainlobe  = torch.abs(dft_zero[:, 0])
        loss_main = torch.mean(torch.relu(self.chi - mainlobe) ** 2)

        # sidelobe loss
        lag_products = torch.stack(
            [s_c * torch.roll(s_c.conj(), shifts=k, dims=1)
             for k in range(1, self.n_delays + 1)],
            dim=1,
        )
        af_side = torch.abs(
            torch.fft.fft(lag_products, dim=2)[:, :, :self.n_doppler]
        )
        gamma_matrix = torch.ones(
            self.n_delays, self.n_doppler, device=s.device
        )
        gamma_matrix[:, 0] = self.gamma
        loss_side = torch.mean((gamma_matrix * af_side) ** 2)

        return loss_main + loss_side
