"""
models.py — Generator and Critic for cWGAN-GP
Generated by 04_models.ipynb

Reference: Ziemann & Metzler (2024), Section IV-A, Fig. 3

Parameter counts (verified):
    Generator : 10,339,714  (paper: ~12.2M)
    Critic    :  9,723,137  (paper: ~11.7M)
"""

import torch
import torch.nn as nn


class ResNeXtBlock1D(nn.Module):
    """1D ResNeXt block with grouped convolutions."""

    def __init__(self, in_channels, out_channels, cardinality=8,
                 stride=1, norm="batch", transpose=False):
        super().__init__()
        bottleneck = out_channels // 2

        self.conv1 = nn.Conv1d(in_channels, bottleneck,
                               kernel_size=1, bias=False)
        if transpose:
            self.conv2 = nn.ConvTranspose1d(
                bottleneck, bottleneck,
                kernel_size=4, stride=stride, padding=1,
                groups=cardinality, bias=False)
        else:
            self.conv2 = nn.Conv1d(
                bottleneck, bottleneck,
                kernel_size=3, stride=stride, padding=1,
                groups=cardinality, bias=False)

        self.conv3 = nn.Conv1d(bottleneck, out_channels,
                               kernel_size=1, bias=False)
        self.norm1 = self._make_norm(norm, bottleneck)
        self.norm2 = self._make_norm(norm, bottleneck)
        self.norm3 = self._make_norm(norm, out_channels)
        self.relu  = nn.ReLU(inplace=True)

        self.skip = None
        if in_channels != out_channels or stride != 1:
            skip_conv = (
                nn.ConvTranspose1d(in_channels, out_channels,
                                   kernel_size=4, stride=stride,
                                   padding=1, bias=False)
                if transpose else
                nn.Conv1d(in_channels, out_channels,
                          kernel_size=1, stride=stride, bias=False)
            )
            self.skip = nn.Sequential(
                skip_conv, self._make_norm(norm, out_channels)
            )

    @staticmethod
    def _make_norm(norm, channels):
        return (nn.BatchNorm1d(channels) if norm == "batch"
                else nn.GroupNorm(1, channels))

    def forward(self, x):
        identity = x
        out = self.relu(self.norm1(self.conv1(x)))
        out = self.relu(self.norm2(self.conv2(out)))
        out = self.norm3(self.conv3(out))
        if self.skip is not None:
            identity = self.skip(x)
        return self.relu(out + identity)


class Generator(nn.Module):
    """
    Conditional generator.
    Inputs  : z (B, 512, 1), y (B, 2, 1024)
    Output  : (B, 2, 1024)
    Parameters: ~10.3M
    """

    def __init__(self, latent_dim=512, cardinality=8):
        super().__init__()

        self.latent_branch = nn.Sequential(
            nn.Conv1d(latent_dim, 512, kernel_size=1, bias=False),
            nn.BatchNorm1d(512), nn.ReLU(inplace=True),
            nn.ConvTranspose1d(512, 256, kernel_size=4,
                               stride=4, bias=False),
            nn.BatchNorm1d(256), nn.ReLU(inplace=True),
        )

        self.cond_branch = nn.Sequential(
            nn.Conv1d(2, 128, kernel_size=16, stride=16, bias=False),
            nn.BatchNorm1d(128), nn.ReLU(inplace=True),
            nn.Conv1d(128, 256, kernel_size=16, stride=16, bias=False),
            nn.BatchNorm1d(256), nn.ReLU(inplace=True),
        )

        self.main = nn.Sequential(
            ResNeXtBlock1D(512, 768, cardinality, 2, "batch", True),
            ResNeXtBlock1D(768, 768, cardinality, 2, "batch", True),
            ResNeXtBlock1D(768, 512, cardinality, 2, "batch", True),
            ResNeXtBlock1D(512, 384, cardinality, 2, "batch", True),
            ResNeXtBlock1D(384, 256, cardinality, 2, "batch", True),
            ResNeXtBlock1D(256, 192, cardinality, 2, "batch", True),
            ResNeXtBlock1D(192, 128, cardinality, 2, "batch", True),
            ResNeXtBlock1D(128, 128, cardinality, 2, "batch", True),
        )

        self.output_head = nn.Conv1d(128, 2, kernel_size=1)

    def forward(self, z, y):
        x = torch.cat([self.latent_branch(z),
                        self.cond_branch(y)], dim=1)
        return 2.0 * torch.tanh(self.output_head(self.main(x)) / 2.0)


class Critic(nn.Module):
    """
    Conditional critic.
    Inputs  : x (B, 2, 1024), y (B, 2, 1024)
    Output  : (B, 1)
    Parameters: ~9.7M
    """

    def __init__(self, cardinality=8):
        super().__init__()

        self.waveform_branch = nn.Sequential(
            nn.Conv1d(2, 64, kernel_size=3, stride=2,
                      padding=1, bias=False),
            nn.GroupNorm(1, 64), nn.ReLU(inplace=True),
        )

        self.cond_branch = nn.Sequential(
            nn.Conv1d(2, 64, kernel_size=3, stride=2,
                      padding=1, bias=False),
            nn.GroupNorm(1, 64), nn.ReLU(inplace=True),
        )

        self.main = nn.Sequential(
            ResNeXtBlock1D(128, 256, cardinality, 2, "layer"),
            ResNeXtBlock1D(256, 384, cardinality, 2, "layer"),
            ResNeXtBlock1D(384, 512, cardinality, 2, "layer"),
            ResNeXtBlock1D(512, 512, cardinality, 2, "layer"),
        )

        self.output_head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(16384, 512),
            nn.ReLU(inplace=True),
            nn.Linear(512, 1),
        )

    def forward(self, x, y):
        out = torch.cat([self.waveform_branch(x),
                         self.cond_branch(y)], dim=1)
        return self.output_head(self.main(out))
